[project]
name = "eggroll-mnist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax[cuda]",
    "numpy",
    "xprof>=2.21.5",
]
